hello/urls.py
from django.urls import path
from . import views
#define a var as a list representing all urls can be accessed with this app

urlpatterns=[
    # path("",views.index,name="index"),
    path("<str:name>", views.greet, name="greet")
    # path("sherif",views.sherif,name="sherif"),
    # path("david",views.david, name="david"),
]

mydjango1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/',include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
    
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index,name="index")
]

tasks/urls.py
from django.urls import path
from . import views

app_name="tasks"

urlpatterns=[
    path("", views.index, name= "index"),
    path("add", views.add, name= "add")
]

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse



# def greet(request,name):
#     #make httprequest to render just a str
#     return HttpResponse(f"Hello,{name.capitalize()}")

# def index(request):
#     # to render the whole html file
#  return render(request,"hello/index.html")

# def sherif(request):
    
#     return HttpResponse("Hello, Sherif :)")

# def david(request):
#     return HttpResponse("Hello, David :)")

def greet(request,name):
    return render(request,"hello/greet.html",{
        "name":name.capitalize()
        
    })
    

newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear":now.month==1 and now.day==1
    })

tasks/views.py
from django.shortcuts import render
from django import forms


tasks=["foo","bar","baz"]

class NewTaskForm(forms.Form):
    task=forms.CharField(label="New task")
    priority= forms.IntegerField(label="Priority", min_value=1, max_value=10)



# Create your views here.
def index(request):
    return render(request, "tasks/index.html",{
        "tasks": tasks
    })
    # Add a new task:
def add(request):
    if request.method=="POST":
        #PROCESS THE RESULT OF THE REQUEST
        #a var contains all data user submitted
        form=NewTaskForm(request.POST)
        #extract clean data as a result of this form
        if form.is_valid():
            #get what task the user submitted
            task = form.cleaned_data(["task"])
            
            #add this task to the list of tasks
            tasks.append(task)
            
            #if the form isn't valid
        else:
            return render(request,"tasks/add.html",{
                #send back the existing form a new form
                "form":form
                
            })
            
            
        
        
        
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{name}}</h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, World, this is a python gen</h1>
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Is it new year</title>
    <link rel="stylesheet" href="{% static "newyear/styles.css" %}">
  </head>
  <body>
    {% if newyear %}
    <h1>Yes</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}
  </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task:</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html"%} 

{% block body %}
<h1>Tasks</h1>
<ul>
  {% for task in tasks %}
  <li>{{task}}</li>
  {%endfor%}
</ul>
<a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>